### ISSUE TITLE
TODO list before CRAN submission

### ISSUE THREAD

**Issue by walkerke** [walkerke/tigris#10]
- [x] Add all remaining geographies
- [x] Give option to download very-generalized cartographic boundary files when applicable
- [ ] Remove warning message (if possible) associated with download progress bar
- [x] Fully document the functions with descriptions from the Census Bureau
- [x] Update the package for the imminent 2015 TIGER/Line shapefiles release
- [ ] Finish vignettes.  I'm thinking three: one for basic usage, one for visualization, and one for spatial analysis.

**Comment by walkerke** [comment]
Re: the progress bar - looks like Hadley fixed this in httr here https://github.com/hadley/httr/commit/d9395f231c1d5225d3d6678d0ad580c22a2196b9 but the fix is not yet on CRAN; once it is we should be OK

**Comment by walkerke** [comment]
Regarding the 2015 shapefiles: the tech docs are already up on the web, and based on the release date for the 2014 files I'd expect to see the 2015 files this month.  The Census continues to host older shapefiles with the same URL scheme (double-check this): perhaps there could be an option users could modify to set the year they'd like to download, defaulting to 2015.

**Comment by walkerke** [comment]
Looking at picking this up again.  Regarding a couple points: 

* Thinking about a refactor for generalized cartographic boundary files as `detailed = FALSE` is not as explicit as it could be.  Considering changing this to `cb = TRUE` to get cartographic boundary files, and then another optional argument, `resolution = '500k'`, in which users can supply `5m` or `20m` instead to get very-simplified files.  
* Instead of vignettes, I'll refer users to the RPubs I've already written as well as the R Journal article I'm preparing, which will cover all of those topics.  

Once this is done, let's send off to CRAN!

**Comment by walkerke** [comment]
A new `cb` parameter refers to cartographic boundary files more explicitly, and when applicable users can set the resolution of their downloaded data.  I've left in the `detailed` parameter with a warning message that it is deprecated and will disappear eventually, but it maintains its old functionality.  

Almost all of the Census datasets are now available.  I'll wait on a few of them until later (address features and edges); New England areas are all that are left to add.  The core Census geographies are fully documented; we can work on others as we go, but I don't know that this should get in the way of a CRAN submission.

**Comment by walkerke** [comment]
All parameters are now documented and the package passes CRAN checks.  Left to do: 

1. Add New England areas
2. Add Census descriptions when available
3. Add examples

After that, it should be ready to go!

**Comment by walkerke** [comment]
@hrbrmstr I've made all of the aforementioned updates and the package is passing CRAN checks.  I think we're just about ready to submit!  The article will accompany the package when it's written - I envision it borrowing heavily from the RPubs I've already written on the package.

**Comment by walkerke** [comment]
Package submitted to CRAN this morning!  Will post CRAN maintainer comments and necessary revisions here, if applicable.

**Comment by walkerke** [comment]
@hrbrmstr `tigris` is now on CRAN!  Submission to acceptance took only a few hours.  I'll be publicizing shortly!
